Added CDK toolkit installation and bootstrap, changed CDK outputs.json
aws-containers/proton-codebuild-provisioning-examples pull request #9
Opened 2022-12-08 19:16 UTC by charan-amzn

2022-12-11 05:02 UTC, adamjkeller requested changes

2022-12-11 05:02 UTC, adamjkeller commented on cdk/environment-templates/vpc-ecs-cluster/v1/infrastructure/manifest.yaml
> +          - cdk bootstrap
we intentionally removed the cdk bootstrap from the manifest and advise users to run this outside of codebuild as there could be potential implications that are region/account wide. This is documented in the README.

2023-01-05 20:02 UTC, charan-amzn commented on cdk/environment-templates/vpc-ecs-cluster/v1/infrastructure/manifest.yaml
> +          - cdk bootstrap
Got it, removed it

2023-01-06 20:18 UTC, adamjkeller approved these changes

2023-01-06 20:18 UTC, merged